### ISSUE TITLE
redirect search button on welcome page to /search, extend html

### ISSUE THREAD

**Issue by siemaaa** [SHWN-Co/eweive#12]
extend html navbars
logged in show on navbar

**Comment by hongweimachene** [comment]
this will be resolved when we make a navbar html that we extend

**Comment by siemaaa** [comment]
https://dev.to/brunooliveira/flask-series-part-9-adding-a-navbar-by-using-template-inheritance-2e5o

@hongweimachene do we have something like: 
`    {% if not (current_user.is_authenticated and current_user.is_active)%}
`
to be used in base.html?
