### ISSUE TITLE
file a report page 

### ISSUE THREAD

**Issue by noelsmathew** [SHWN-Co/eweive#21]
file a report page has 2 nav bars on it after clicking from the items page, seems to be old nav bar with current. 
<img width="1440" alt="Screen Shot 2022-12-10 at 4 07 23 AM" src="https://user-images.githubusercontent.com/53527019/206842518-f41e4d8d-fde2-4626-8e93-7a8f8e67dd59.png">

**Comment by siemaaa** [comment]
oopsie! this will be an easy fix, we can update this on Monday. It's just removing the existing div code on html

**Comment by siemaaa** [comment]
fixed
